import Header from "@/app/_components/Header";
import "@/styles/globals.css";

import { Roboto_Slab } from "next/font/google";
import { type ReactElement } from "react";

const Roboto = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }): ReactElement {
  return (
    <html lang="en">
      <body className={`font-sans ${Roboto.variable} bg-[#000C36]`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
